project:
  type: website

website:
  title: "Tyler Bonnell"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: yeti
    css: styles.css
    toc: false

editor: visual

