project:
  type: website
  preview:
    port: 4996
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto
    
website:
  favicon: assets/images/Logo.webp
  repo-url: https://github.com/Tyler-Bonnell/tyler-bonnell-website
  repo-actions:
    - source
    - issue
  search: true
  
  navbar:
    title: "TYLER<span class='icon-line'></span>BONNELL"
    pinned: true
    right: 
      - text: About
        icon: person-fill
        href: index.qmd
      - text: Experience
        icon: file-text-fill
        href: cv.qmd
      - text: Projects
        icon: code-slash
        href: projects.qmd
      - text: Resources
        icon: database-fill-gear
        href: resources.qmd
  page-footer:
    border: true
    left: "&#169; 2024 Tyler Bonnell"
    center:
      - text: Code of Conduct
        href: code_of_conduct.qmd
      - text: Acknowledgements
        href: acknowledgements.qmd
      - text: License
        href: license.qmd
    right: "Made with [Quarto](https://quarto.org), Maintained in [{{< fa brands r-project >}}](https://www.r-project.org/), and Styled with [CSS](https://en.wikipedia.org/wiki/CSS#CSS_3)."
  cookie-consent:
    type: express
    prefs-text: "Cookie Preferences"

format:
  html:
    theme:
      light: [yeti, assets/styling/styles.scss]
      dark: [darkly, assets/styling/styles_dark.scss]
    toc: true
    toc-depth: 4
    pagetitle: "Tyler Bonnell | {{< meta title >}}"
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y