project:
  type: website
  preview:
    port: 4996
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto
    
website:
  title: "Tyler Bonnell"
  favicon: assets/images/Logo4.webp
  repo-url: https://github.com/Tyler-Bonnell/tyler-bonnell-website
  repo-actions:
    - source
    - issue
  search:
    type: textbox
  back-to-top-navigation: true
  
  navbar:
    pinned: true
    logo: assets/images/Logo4-nobg.webp
    logo-alt: "Initials T J B in diagonal pattern."
    left:
      - text: About
        icon: person-fill
        href: index.qmd
      - text: Experience
        icon: file-text-fill
        href: cv.qmd
      - text: Projects
        icon: code-slash
        href: projects.qmd
      - text: Resources
        icon: database-fill-gear
        href: data_science_resources.qmd
    right: 
      - icon: briefcase-fill
        aria-label: Work
        href: https://doh.wa.gov/public-health-healthcare-providers/healthcare-professions-and-facilities/data-exchange/syndromic-surveillance-rhino
      - icon: github
        aria-label: GitHub
        menu:
          - text: GitHub Profile
            url: https://github.com/Tyler-Bonnell
          - text: Source Code
            url:  https://github.com/Tyler-Bonnell/tyler-bonnell-website
          - text: Report an Issue
            url:  https://github.com/Tyler-Bonnell/tyler-bonnell-website/issues
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/tylerjbonnell/
      - icon: send
        aria-label: Email
        href: mailto:tylerbonnell.j@gmail.com
  page-footer:
    border: true
    left: "&#169; 2024 Tyler Bonnell"
    center:
      - text: Code of Conduct
        href: code_of_conduct.qmd
      - text: License
        href: license.qmd
    right: "Made with [Quarto](https://quarto.org), Maintained in [R](https://www.r-project.org/), and Styled with [CSS](https://en.wikipedia.org/wiki/CSS#CSS_3)."
  cookie-consent:
    type: express

format:
  html:
    theme:
      light: 
        - yeti
        - assets/styling/styles.scss
      dark: 
        - darkly
        - assets/styling/styles_dark.scss
    toc: true
    toc-depth: 4
    pagetitle: "Tyler Bonnell | {{< meta title >}}"
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y