project:
  type: website
  preview:
    port: 4996
    browser: true
    watch-inputs: true
    timeout: 3600

website:
  title: "Tyler Bonnell"
  repo-url: https://github.com/Tyler-Bonnell/tyler-bonnell-website
  repo-actions:
    - source
    - issue
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right: 
      - icon: briefcase-fill
        aria-label: Work
        href: https://doh.wa.gov/public-health-healthcare-providers/healthcare-professions-and-facilities/data-exchange/syndromic-surveillance-rhino
      - icon: github
        aria-label: GitHub
        menu:
          - text: GitHub Profile
            url: https://github.com/Tyler-Bonnell
          - text: Source Code
            url:  https://github.com/Tyler-Bonnell/tyler-bonnell-website
          - text: Report an Issue
            url:  https://github.com/Tyler-Bonnell/tyler-bonnell-website/issues

      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/tylerjbonnell/

format:
  html:
    theme: [flatly, assets/styling/theme.scss]
    toc: true
    toc-depth: 4
    pagetitle: "Tyler Bonnell | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y